In [4]:
#preprocess step

import pandas as pd
from sklearn.impute import KNNImputer
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder
from pandas.api.types import CategoricalDtype


# FUNCTION TO HANDLE OUTLIERS
def handle_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df = df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]
    return df


# MOVIES DATASET
movies_df = pd.read_csv(r"C:\Users\nh013\Desktop\movie recommendation system dataset\movies.csv")


#RATINGS DATASET
ratings_df = pd.read_csv(r"C:\Users\nh013\Desktop\movie recommendation system dataset\ratings.csv")


# MOVIES DATAFRAME FEATURE EXTRACT
movies_df = movies_df[['movieId', 'title', 'genres']]



# FEATURE EXTRACT RATING DATAFRAME 
ratings_df = ratings_df[['userId', 'movieId', 'rating', 'timestamp']]



# CHECK MISSING VALUES
movies_df.dropna(inplace=True)
ratings_df.dropna(inplace=True)



# HANDLE OUTLIERS
movies_df = handle_outliers(movies_df, 'movieId')
ratings_df = handle_outliers(ratings_df, 'rating')

#NORMALIZE AND SCLAE NUMERIC COLUMN TO MOVIES DATAFRAME 
numeric_cols_movies = ['movieId']
scaler = MinMaxScaler()
movies_df[numeric_cols_movies] = scaler.fit_transform(movies_df[numeric_cols_movies])


# NORMALIZE AND SCLAE NUMERIC COLUMN TO RATING DATAFRAME
numeric_cols_ratings = ['rating']
scaler = StandardScaler()
ratings_df[numeric_cols_ratings] = scaler.fit_transform(ratings_df[numeric_cols_ratings])



# CONVERT CATEGORICAL VALUES TO NUMERICAL TO MOVIES DTAFRAME 
categorical_cols_movies = ['title', 'genres']
for col in categorical_cols_movies:
    cat_type = CategoricalDtype(categories=movies_df[col].unique(), ordered=True)
    movies_df[col] = movies_df[col].astype(cat_type).cat.codes

    
    
# CONVERT CATEGORICAL VALUES TO NUMERICAL TO RATING DATAFRAME
categorical_cols_ratings = ['userId']
for col in categorical_cols_ratings:
    cat_type = CategoricalDtype(categories=ratings_df[col].unique(), ordered=True)
    ratings_df[col] = ratings_df[col].astype(cat_type).cat.codes

    
    
#ONE HOT ENCODING TO MOVIES DATAFRAME
movies_df_encoded = pd.get_dummies(movies_df, columns=categorical_cols_movies, sparse=True)

#ONE HOT ENCODING TO RATING DATAFRAME
ratings_df_encoded = pd.get_dummies(ratings_df, columns=categorical_cols_ratings, sparse=True)



print("Movies DataFrame:")
print(movies_df_encoded.head())

print("Ratings DataFrame:")
print(ratings_df_encoded.head())

Movies DataFrame:
    movieId  title_0  title_1  title_2  title_3  title_4  title_5  title_6  \
0  0.000000        1        0        0        0        0        0        0
1  0.000005        0        1        0        0        0        0        0
2  0.000010        0        0        1        0        0        0        0
3  0.000014        0        0        0        1        0        0        0
4  0.000019        0        0        0        0        1        0        0

   title_7  title_8  ...  genres_1629  genres_1630  genres_1631  genres_1632  \
0        0        0  ...            0            0            0            0
1        0        0  ...            0            0            0            0
2        0        0  ...            0            0            0            0
3        0        0  ...            0            0            0            0
4        0        0  ...            0            0            0            0

   genres_1633  genres_1634  genres_1635  genres_1636  genres_1637  \
0            0            0            0            0            0
1            0            0            0            0            0
2            0            0            0            0            0
3            0            0            0            0            0
4            0            0            0            0            0

   genres_1638
0            0
1            0
2            0
3            0
4            0

[5 rows x 63965 columns]
Ratings DataFrame:
   movieId    rating   timestamp  userId_0  userId_1  userId_2  userId_3  \
0      296  1.489314  1147880044         1         0         0         0
1      306 -0.185948  1147868817         1         0         0         0
2      307  1.489314  1147868828         1         0         0         0
3      665  1.489314  1147878820         1         0         0         0
4      899 -0.185948  1147868510         1         0         0         0

   userId_4  userId_5  userId_6  ...  userId_162513  userId_162514  \
0         0         0         0  ...              0              0
1         0         0         0  ...              0              0
2         0         0         0  ...              0              0
3         0         0         0  ...              0              0
4         0         0         0  ...              0              0

   userId_162515  userId_162516  userId_162517  userId_162518  userId_162519  \
0              0              0              0              0              0
1              0              0              0              0              0
2              0              0              0              0              0
3              0              0              0              0              0
4              0              0              0              0              0

   userId_162520  userId_162521  userId_162522
0              0              0              0
1              0              0              0
2              0              0              0
3              0              0              0
4              0              0              0

[5 rows x 162526 columns]